 Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: database
      MARIADB_USER:  user
      MARIADB_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    environment:
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: pepa-linha-dark
    ports:
      - 8080:8080              
volumes:
    mariadb:

# mariadb --protocol=tcp -u root -p
