
version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./config/mariadb.env
    ports:
      - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
    depends_on: 
      - mariadb

volumes:
  mariadb:

# mariadb --protocol=tcp -u root -p
